version: "3"
services:
    server:
     image: clickhouse/clickhouse-server
     ports:
     - "8123:8123"
     - "9001:9000"
     - "9009:9009"
     
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
    client:
      image: clickhouse/clickhouse-client
      command: ['--host', 'server']

   